### ISSUE TITLE
w9xpopen0.exe !!!

### ISSUE THREAD

**Issue by sparta3407** [lfasmpao/python-fud-payload#1]
hi lfasmpao,first thanks for this job , but what is the role of the second file generated "w9xpopen0.exe" !!!
and i use a netcat as listener is that enough!!

**Comment by lfasmpao** [comment]
This is okay sir. You can distribute the file without the w9xopen.exe :)

**Comment by sparta3407** [comment]
ok thanks for reply

**Comment by lfasmpao** [comment]
You can now fork the latest build :)
